// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tradebuzz-redesign/MidnightFinance.tsx": () => import("../components/mockups/tradebuzz-redesign/MidnightFinance.tsx"),
  "./components/mockups/tradebuzz-redesign/ObsidianNoir.tsx": () => import("../components/mockups/tradebuzz-redesign/ObsidianNoir.tsx"),
  "./components/mockups/tradebuzz-redesign/TerminalPro.tsx": () => import("../components/mockups/tradebuzz-redesign/TerminalPro.tsx")
};
